/**
@copyright MIT license; see @ref index or the accompanying LICENSE file.

@file
@brief Unconfigure GR.
*/

#include <duct/GR/undefine.hpp>

#undef CACOPHONY_DETAIL_GR_CORE_HPP_
#undef CACOPHONY_SCOPE_CLASS
#undef CACOPHONY_SCOPE_FUNC
#undef CACOPHONY_SCOPE_FQN_STR
#undef CACOPHONY_THROW
#undef CACOPHONY_THROW_CLASS
#undef CACOPHONY_THROW_FUNC
#undef CACOPHONY_THROW_FQN

#undef CACOPHONY_DETAIL_GR_CEFORMAT_HPP_
#undef CACOPHONY_DEF_FMT
#undef CACOPHONY_DEF_FMT_CLASS
#undef CACOPHONY_DEF_FMT_FUNC
#undef CACOPHONY_DEF_FMT_FQN
#undef CACOPHONY_THROW_FMT
